### ISSUE TITLE
Precision Landing - EKF2's auxiliary velocity aiding

### ISSUE THREAD

**Issue by hamishwillee** [PX4/px4_user_guide#136]
Need to update  [Precision Landing · PX4 User Guide](https://docs.px4.io/en/advanced_features/precland.html) with information about EKF2's auxiliary velocity aiding (added after the docs were created).

Originates from https://github.com/PX4/Firmware/pull/8676#issue-288384578

@mhkabir Assigned to you in first case. OK?

**Comment by ndepal** [comment]
See https://github.com/PX4/px4_user_guide/pull/132

**Comment by hamishwillee** [comment]
Thanks. Merged and closed!
