### ISSUE TITLE
Proposed flight mode docs structure and iconography

### ISSUE THREAD

**Issue by hamishwillee** [PX4/px4_user_guide#178]
This proposal is that we simplify the structure to make it easier to navigate, and use better iconography to provide needed context when you are within the document.

**Background**

The current structure for [Flight Modes Overview](https://docs.px4.io/en/getting_started/flight_modes.html) sorts flight modes by vehicle, type of mode (e.g. auto, manual).  It is quite hard to read because it is so large. When you are inside the document and reading a particular flight mode it is easy to lose track of the fact that you're in MC or FW. There is also repetition of some of the grouping information (auto, manual, assisted). 

My thought is that while it is useful to know there are different categories of modes and to group the modes by category, it is not necessary to have this grouping marked by a heading in the TOC. 

**Proposal: Improve structure:**
1. List the modes in each category in the category overview like this:
  ![image](https://user-images.githubusercontent.com/5368500/37753519-7d195344-2df1-11e8-8fef-c21b63ceea0a.png)

2. Remove the headings for manual, assisted, auto modes in the TOC so everything is just sorted by vehicle (but still grouped with others in same category)
   - With only one parent heading, it is much easier to know you are in MC or FW
   - There is no duplication of the information about categories.
  ![image](https://user-images.githubusercontent.com/5368500/37753542-91580af8-2df1-11e8-845f-47250aa8027c.png)

**Proposal: Improve icons:**

The proposal is to add a bar of icons in each of the modes. This will provide additional context in the same way that the GPS icon currently does (though we should if possible change that because it implies "GPS" and we support other position technologies). 

We could have icons for:
- Requires position
- Requires remote control (manual or assisted) - I don't think we need an "assisted" icon.
- Does not require remote control (Auto) - ie remote control crossed out?
- Vehicle (e.g. MC icon indicates this is MC mode)
- Other ?

For example:
  
![image](https://user-images.githubusercontent.com/5368500/37753690-40311010-2df2-11e8-9173-f85f57f3479c.png)

@tubeme @bkueng @barzanisar - What do you think? What icons should we use? 

----

Discussion was [originally here](https://github.com/PX4/px4_user_guide/pull/175#issuecomment-375189471) (closed PR).

**Comment by hamishwillee** [comment]
FYI some possible icons: 

----

A few other icons are listed below....

* ![image](https://user-images.githubusercontent.com/5368500/37748982-ea102b8e-2dd9-11e8-9c5d-d8c9f112a919.png) - [from here](https://www.flaticon.com/free-icon/gps-fixed-indicator_60834)
* ![image](https://user-images.githubusercontent.com/5368500/37749041-2a9dbf0e-2dda-11e8-8592-f1f3d9faabd2.png)  - [from here](https://www.iconfinder.com/icons/126573/gps_location_map_pin_icon#size=32)


* ![image](https://user-images.githubusercontent.com/5368500/37749076-62d29516-2dda-11e8-8757-eb5b5c8cd889.png) - from [here](https://www.google.com.au/search?q=free+small+icon+gps&dcr=0&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwiTve2Y-P7ZAhVBjpQKHW4ID7kQ7AkINg&biw=1229&bih=587#imgrc=rlid6HG39D63OM:)

And maybe this one for rc:
![image](https://user-images.githubusercontent.com/5368500/37749240-2fff146a-2ddb-11e8-8373-5603ea15b37e.png)
 (from [here](http://www.adelaideadvertising.com/free-drone-icon-design-to-download/)

**Comment by hamishwillee** [comment]
@tubeme Very much leaning towards at least doing the restructure proposed above. In the [flight mode table](https://docs.px4.io/en/flight_modes/flight_modes_summary.html#multicopter) you will see that I don't organise by assisted/manual so I can relate each mode to the one before. 

ie restructuring would allow me to reorder the modes and use the "ladder principle" you suggested.

**Comment by bkueng** [comment]
I like your proposal - and the set of icons. Maybe add one that shows the level of difficulty?
For the position icon, I would probably go for https://www.flaticon.com/free-icon/gps-fixed-indicator_60834.

**Comment by hamishwillee** [comment]
Thanks. OK, so first part done (reorg - not icons): https://github.com/PX4/px4_user_guide/pull/183

**Comment by tubeme** [comment]
Looks good to me. I got some icons I noticed that can be used for positioning device as well.
![simbolo ubicacion](https://user-images.githubusercontent.com/12617619/37894480-157649d8-30e7-11e8-99f7-29c7e535f0da.png)
![images](https://user-images.githubusercontent.com/12617619/37894485-17f403b2-30e7-11e8-9415-ec7f9b21c2b6.png)
![18576fb0f4edfe5](https://user-images.githubusercontent.com/12617619/37894490-19864a8c-30e7-11e8-9d7b-b3579281d410.jpg)

For the difficulty level the icon is too detailed for the small size it appears on the page.

So probably using just a dot with a color will be more iconic and easy to perceive.

We can use green, yellow and red like in the traffic lights?

**Comment by tubeme** [comment]
This one is not bad at all and has signature to it.
![location device](https://user-images.githubusercontent.com/12617619/37903815-fc5c3bae-3101-11e8-8dc8-bbb6e5cb3f78.png)

**Comment by hamishwillee** [comment]
@tubeme I do like that last position image, but it is a "paid for" one. I used a similar icon that was free as shown below. Updated the difficulty icon using number and and colour as you suggested - decided to have the 6 level options. 

![image](https://user-images.githubusercontent.com/5368500/37941715-4bdbf03e-31bb-11e8-92e2-7b73ebc05637.png)

Better options still welcome! If you do find one though, please provide URL.

**Comment by hamishwillee** [comment]
Closing this, as it is being addressed in https://github.com/PX4/px4_user_guide/pull/184
