### ISSUE TITLE
[For improve] Procedure Clarification - Doc Bug: Airspeed · PX4 User Guide

### ISSUE THREAD

**Issue by bigbellmercy** [PX4/px4_user_guide#193]
Hi, Thanks for User Guide.

The airspeed calibration procedure need more clarification of meaning for novices to do it.
Following is my question during my calibration failures:

4. Cover the sensor (i.e. with your hand). --> For what? To protect wind from the sensor?
6. Blow across the sensor. --> By mouth?, or some blowing device is needed?
As the 'Create air pressure!' is displayed, how many times should we blow by mouth?
And how much is the separation distance form the tip to mouth in side? 1 cm is enough?

Bug Page: [Airspeed · PX4 User Guide](https://docs.px4.io/en/config/airspeed.html)

**Comment by bigbellmercy** [comment]
The other [post](http://discuss.px4.io/t/airspeed-sensor-calibration/5083) requests the same request as mine.

After I've succeeded in the calibration, I noticed the problem the document:

The key point of my mistake was that I was blowing air by mouth perpendicular to the pitot tube because of the sentence 'Blow **across** the sensor'.
After I blow air **parallel** to the pitot tube **by mouth shortly** in front of the tip of pitot tube, calibration did not failed.
Other people also seems to misunderstand the expression '**across**' so it'd rather to be changed.

**Comment by hamishwillee** [comment]
Thank you. I've clarified that you blow INTO the pitot in https://github.com/PX4/px4_user_guide/pull/194 - feel free to comment.

**Comment by bigbellmercy** [comment]
Thanks a lot, Nice change!
