### ISSUE TITLE
Doc Bug: Flight Modes · PX4 User Guide

### ISSUE THREAD

**Issue by bigbellmercy** [PX4/px4_user_guide#213]
Hi, in 'Position' and 'Altitude' modes of 'Fixed Wing', there is no description for 'yaw stick'.

So users including me cannot know how the heading is determined and what is the role of yaw stick.

Bug Page: [Flight Modes · PX4 User Guide](https://docs.px4.io/en/flight_modes/)

**Comment by hamishwillee** [comment]
Hmmm. Yaw stick controls yaw :-) Do you think we need to add that to the list?

This is very much a summary. At the top of the page you will see this link: https://docs.px4.io/en/getting_started/flight_modes.html

Thoughts?

**Comment by bigbellmercy** [comment]
Nice day~ I agree. You’d rather decide to change or only consider it later. I just informed my case.

**Comment by hamishwillee** [comment]
Thanks @bigbellmercy Done!

**Comment by bigbellmercy** [comment]
Great Hamish!
