### ISSUE TITLE
PX4 User Guide site appears to be broken

### ISSUE THREAD

**Issue by seanrowens** [PX4/px4_user_guide#260]
If I google on;

PX4 user guide

google shows me a top hit of;

> Introduction · PX4 User Guide
> https://docs.px4.io/en/
> Getting Started should be read by all users! It provides an overview of PX4, including features provided by the flight stack (flight modes and safety features) and ...

Clicking on the above link takes me to https://px4.gitbook.io/px4-user-guide which appears to be pretty much empty.  Screenshot attached.

![screen shot 2018-06-13 at 6 36 40 pm](https://user-images.githubusercontent.com/1154707/41382149-d2312176-6f38-11e8-8547-d19478bf7b47.png)

**Comment by hamishwillee** [comment]
Yes it is. We're looking into it. Thanks.

**Comment by hamishwillee** [comment]
And for now, you can access current content from here: 
https://hamishwillee.gitbooks.io/havdevguide/content/en/
https://hamishwillee.gitbooks.io/ham_px4userguide/content/

**Comment by seanrowens** [comment]
Many thanks, that helps.

**Comment by hamishwillee** [comment]
Fixed! Thanks for reporting this.

**Comment by seanrowens** [comment]
Thanks for making some awesome open source software and (especially!) docs!
