### ISSUE TITLE
Lidar-Lite misleading note for the Intel Aero

### ISSUE THREAD

**Issue by IeiuniumLux** [PX4/px4_user_guide#294]
Hi Hamish,

The [Lidar-Lite page](https://github.com/PX4/px4_user_guide/blob/67745a094608bcaaca9c4452f3b078270d4083ad/en/sensor/lidar_lite.md#lidar-lite) has a little bit misleading note for the Intel Aero. The note links you to the Intel Aero page just to find out a [waring](https://github.com/PX4/px4_user_guide/blob/df32443e5fbb14240270a26e93526f7ddeccfd0b/en/flight_controller/intel_aero.md#connecting-lidar-lite-range-finder-lidar_lite) actually not recommending to use it with the Intel Aero. If the warning for the Intel Aero is correct, then it's probably better to add it to the Lidar-Lite page as well. Unless that waring only applies to the previous v2 version of the sensor.

Also, notice that the first picture at the top of the The [Lidar-Lite page](https://github.com/PX4/px4_user_guide/blob/67745a094608bcaaca9c4452f3b078270d4083ad/en/sensor/lidar_lite.md#lidar-lite) shows the latest v3 version of the sensor; which now has [a different connector and pin layout sequence](http://static.garmin.com/pumac/LIDAR_Lite_v3_Operation_Manual_and_Technical_Specifications.pdf). However, the [wiring section](https://github.com/PX4/px4_user_guide/blob/67745a094608bcaaca9c4452f3b078270d4083ad/en/sensor/lidar_lite.md#wiring) shows the previous version of the sensor; which users should not follow to connect the latest v3 model since as shown below the pin sequence is different.  Therefore, I suggest to add a waring in that section.

<img width="469" alt="screen shot 2018-07-17 at 9 34 09 am" src="https://user-images.githubusercontent.com/3729432/42831948-9d779d94-89a4-11e8-99a5-ae7127de8e47.png">

**Comment by IeiuniumLux** [comment]
@hamishwillee sorry, I was out for a few days.  Yes, that is what I meant regarding the connector being flipped over so you got it.  The pins are on opposite sides in v3 unit. Thanks!

**Comment by hamishwillee** [comment]
Thanks Al, I've made that clear now on master.
