### ISSUE TITLE
Pixracer: broken links

### ISSUE THREAD

**Issue by bkueng** [PX4/px4_user_guide#297]
The links to the schematics (pdf's) are broken: 
https://docs.px4.io/en/flight_controller/pixracer.html#schematics

Should probably include or point to this: https://github.com/AUAV-OpenSource/FMUv4-PixRacer/blob/master/R12%20Initial%20Production/PIXRACER-R12.pdf

**Comment by hamishwillee** [comment]
Thanks Beat. Problem caused by .gitignore hiding pdfs.
Fixed by #299

**Comment by bkueng** [comment]
Thanks!
