### ISSUE TITLE
Doc Bug: Optical Flow · PX4 User Guide

### ISSUE THREAD

**Issue by SrgGroot** [PX4/px4_user_guide#313]
If connected to PX4 via MAVLink the Optical Flow device must publish to the OPTICAL_FLOW_RAD topic, and the distance sensor **must** (not much) publish to the DISANCE_SENSOR topic.

Bug Page: [Optical Flow · PX4 User Guide](https://docs.px4.io/en/sensor/optical_flow.html)

**Comment by hamishwillee** [comment]
Thanks @SrgGroot - much appreciated. Fixed. You can do this sort of fix yourself pretty easily by pressing the Edit button up the top of every page - this will allow you to make a PR for review.

**Comment by SrgGroot** [comment]
Thanks for the friendly reminder!
