### ISSUE TITLE
Miss pid_tuning_guide for both multicoptor and fixed wing in Crowdin

### ISSUE THREAD

**Issue by bys1123** [PX4/px4_user_guide#408]
Can't find pid_tuning_guide_fixedwing.md and pid_tuning_guide_multicopter.md files in PX4-user-guide crowdin translation platform. Do you know why cause this? Could you help fix this?

**Comment by hamishwillee** [comment]
Fixed :-)

It is a minor problem with Crowdin that you can trigger by re-saving the unmodified Github sync config.
