### ISSUE TITLE
Fix warning statement in Camera Trigger page

### ISSUE THREAD

**Issue by IeiuniumLux** [PX4/px4_user_guide#410]
Please replace the first '_**are**_' with an '_**and**_' in the [warning statement](https://github.com/PX4/px4_user_guide/blob/15a269f1565032c4e2f16ac8a43042ee595b6159/en/peripherals/camera.md#trigger-hardware-configuration), as shown below:

"(1234 ~~**_are_**~~ **_and_** 56 are 2 different groups handled by 2 timers)"

**Comment by hamishwillee** [comment]
Thanks. Fixed by https://github.com/PX4/px4_user_guide/commit/2d98fbb8b400d1a7bb901c0681b3d81c759bb0eb
