### ISSUE TITLE
Crazyflie 2.0 Where is CONFIG_DEV_LOWCONSOLE/nuttx-config?

### ISSUE THREAD

**Issue by hamishwillee** [PX4/px4_user_guide#486]
[Crazyflie 2.0 · PX4 User Guide](https://docs.px4.io/master/en/complete_vehicles/crazyflie2.html#flashing-px4)

Has this line

> If QGroundControl does not connect with the vehicle, ensure that in nuttx-config for crazyflie # CONFIG_DEV_LOWCONSOLE is not set is replaced by CONFIG_DEV_LOWCONSOLE=y

But nuttx-config is not at https://github.com/PX4/Firmware/blob/master/platforms/nuttx/nuttx-configs/crazyflie/nsh/defconfig#L934 and search does not find CONFIG_DEV_LOWCONSOLE

What should this say/where is the link?

**Comment by dagar** [comment]
All board specifics are under `boards/` now. Here's the updated link.
https://github.com/PX4/Firmware/blob/master/boards/bitcraze/crazyflie/nuttx-config/nsh/defconfig

The defconfigs have also been compressed, which means they only contain the non-default values. For changing defconfig values you really should use `menuconfig`.

    `make bitcraze_crazyflie_default menuconfig`
  or 
    `make bitcraze_crazyflie_default qconfig`
