### ISSUE TITLE
Aero Ready to Fly Drone - SENS_EN_LEDDAR1 errpr

### ISSUE THREAD

**Issue by hamishwillee** [PX4/px4_user_guide#487]
On [Intel® Aero Ready to Fly Drone](https://docs.px4.io/master/en/complete_vehicles/intel_aero.html) there is a link to SENS_EN_LEDDAR1 that has been replaced by SENS_LEDDAR1_CFG

What port option is this in QGC? TELEM1?

**Comment by bkueng** [comment]
Yes it's telem1
