### ISSUE TITLE
Omnibus F4 SD - which board on hobbywing?

### ISSUE THREAD

**Issue by hamishwillee** [PX4/px4_user_guide#491]
[Omnibus F4 SD](https://docs.px4.io/master/en/flight_controller/omnibus_f4_sd.html#where-to-buy) first "where to buy link" is broken - ie where it says 

> These are the boards tested and known to work:
>   - Hobbywing XRotor Flight Controller F4

Which one of these boards is the actual link here: http://a.hobbywing.com/category.php?id=76&filter_attr=.

**Comment by bkueng** [comment]
This one is the replacement: http://a.hobbywing.com/goods.php?id=636&filter_attr=
I can confirm it's working.

**Comment by hamishwillee** [comment]
Thanks!
