### ISSUE TITLE
TBS Caipiroshka (Pixracer) - links no longer available

### ISSUE THREAD

**Issue by hamishwillee** [PX4/px4_user_guide#494]
[TBS Caipiroshka (Pixracer) · PX4 User Guide](https://docs.px4.io/master/en/frames_vtol/vtol_tailsitter_caipiroshka_pixracer.html)

These links are reporting as broken
- ./_book/en/frames_vtol/vtol_tailsitter_caipiroshka_pixracer.html
  *  External link http://www.eflight.ch/pi/ePower-X-22081.html failed: 404 No error
  *  External link http://www.eflight.ch/shop/USER_ARTIKEL_HANDLING_AUFRUF.php?von_suchresultat=true&Ziel_ID=19638&Kategorie_ID=110923 failed: 404 No error
  *  External link http://www.hobbyking.com/hobbyking/store/__67014__Quanum_MT_Series_2208_1800KV_Brushless_Multirotor_Motor_Built_by_DYS.html failed: 404 No error
  
  Any idea where I can get them?

**Comment by bkueng** [comment]
The Caipirinha is probably not available anymore, but there's the version 2 that might work as well: https://team-blacksheep.com/products/prod:tbs_caipi2_pnp

**Comment by hamishwillee** [comment]
Thanks. I added that link, but there are still the other ones above missing. I'll close this and let's follow up in PR above.
