### ISSUE TITLE
The whole block diagram control scheme with all regulators 

### ISSUE THREAD

**Issue by firegrock** [PX4/px4_user_guide#504]
Hello! 

Where I can found the whole block diagram control scheme of px4 with all levels of regulators in which one can be seen all params of PIDs (mc_pitchrate_p, mc_yawrate_d and e.t.c.)? 

Thank you!

**Comment by hamishwillee** [comment]
In the developer guide, at and below this point: https://dev.px4.io/master/en/concept/architecture.html
