### ISSUE TITLE
Intel Aero Ready to Fly Drone links are broken

### ISSUE THREAD

**Issue by roberthdevries** [PX4/px4_user_guide#529]
The first two links in the article [Intel Aero Ready to Fly Drone](https://docs.px4.io/v1.9.0/en/complete_vehicles/intel_aero.html#intel-aero-ready-to-fly-drone) that point to https://software.intel.com/en-us/aero/dev-kit are broken.

Apparently the Intel Aero product is [discontinued](https://www.intel.com/content/www/us/en/support/products/97174/drones/development-drones/intel-aero-products.html).

**Comment by hamishwillee** [comment]
Thanks. This is true. We're having a discussion internally in the dev team about whether this is the right time to mark the vehicle as such. I'm going to make an executive decision to do so :-). PR to follow.
