### ISSUE TITLE
D-Shot ESCs and Motor Docs

### ISSUE THREAD

**Issue by hamishwillee** [PX4/px4_user_guide#560]
Create DShot page as sub-page of [ESCs & Motors · PX4 User Guide](http://docs.px4.io/master/en/peripherals/esc_motors.html). This is dependent on https://github.com/PX4/Firmware/pull/12634

Discussion 
- https://github.com/PX4/Firmware/pull/12634#issuecomment-521944474
- https://github.com/PX4/Firmware/pull/12634#issuecomment-521828037

**Comment by bys1123** [comment]
This is merged PX4/Firmware#12854, looking forward the documentation.

**Comment by bkueng** [comment]
Docs are also completed: https://github.com/PX4/px4_user_guide/pull/578
https://docs.px4.io/master/en/peripherals/dshot.html
