### ISSUE TITLE
Doc Bug: Pixhawk 4 Mini Wiring Quickstart · PX4 v1.9.0 User Guide

### ISSUE THREAD

**Issue by torbrodtkorb** [PX4/px4_user_guide#585]
Mislabled voltage sensor, should be 0-60V note text below.

The pinout of the Pixhawk 4 Mini POWER port is shown below. The CURRENT signal should carry an analog voltage from 0-3.3V for 0-120A as default. The VOLTAGE signal should carry an analog voltage from 0-3.3V for **0-60A** as default. The VCC lines have to offer at least 3A continuous and should default to 5.1V. A lower voltage of 5V is still acceptable, but discouraged.

Bug Page: [Pixhawk 4 Mini Wiring Quickstart · PX4 v1.9.0 User Guide](https://docs.px4.io/v1.9.0/en/assembly/quick_start_pixhawk4_mini.html#)

**Comment by hamishwillee** [comment]
Thanks very much. Fixed in this version by https://github.com/PX4/px4_user_guide/commit/5fcc1266ed16490f32d3a1e9c4ee468883ffb641 and in master branch of docs by https://github.com/PX4/px4_user_guide/commit/bc2caac31a53fd99854683beea50c98d6facbfa8
