### ISSUE TITLE
Doc Bug: Developer Environment Installation · PX4 v1.9.0 User Guide

### ISSUE THREAD

**Issue by Gdesert** [PX4/px4_user_guide#629]
DESCRIBE PROBLEM WITH DOCS HERE

Bug Page: [Developer Environment Installation · PX4 v1.9.0 User Guide](https://docs.px4.io/v1.9.0/en/flight_controller/snapdragon_flight_dev_environment_installation.html)

**Comment by hamishwillee** [comment]
Looks like a false post.
