### ISSUE TITLE
USB Port numbers and version are very confusing in PX4 Vision Kit docs

### ISSUE THREAD

**Issue by bys1123** [PX4/px4_user_guide#699]
Suggest use USB 2.0/3.0 for version numbers.
![image](https://user-images.githubusercontent.com/4748411/77677051-213dda00-6fca-11ea-89b4-260147091e85.png)
![image](https://user-images.githubusercontent.com/4748411/77677084-2d299c00-6fca-11ea-9b7e-3e627cad46fa.png)
@Jaeyoung-Lim

**Comment by Jaeyoung-Lim** [comment]
@bys1123 Thanks for the feedback. Would it be possible to open a PR that fixes the confustion? thanks

**Comment by bys1123** [comment]
@Jaeyoung-Lim No problem, I'll do that tomorrow.

**Comment by hamishwillee** [comment]
@Jaeyoung-Lim @bys1123 I made the fixes in https://github.com/PX4/px4_user_guide/commit/ed17b1e1000e8e426f69868c41f3f1d9129188f6

BUT this is not the solution. The solution is for the casing to be given better labeling - i.e. USB1 > USB-1, USB2 > USB-2, UART1 to UART-1
@jinger26 Can you request this?

**Comment by bys1123** [comment]
Why? I don't see many products labeled with "-" on casing.

**Comment by bys1123** [comment]
It makes you can only see the "-" when you first get the product.
Same - element - are - easy - to - be - connected - in - your - mind

**Comment by hamishwillee** [comment]
@bys1123 Because every time someone sees USB2 or USB3 on the case they think it is a USB2 or USB3 port.

@jinger26 Perhaps a better way might be to use a #. So `USB#1`, `USB#2` - since # actually means "number".

**Comment by bys1123** [comment]
I would suggest `USB①` `USB②` `USB③`

**Comment by hamishwillee** [comment]
Sure. I don't care as long as it is clearly a number and not a USB version :-)

**Comment by bys1123** [comment]
Just checked some designs, is the numerical layout really necessary
![image](https://user-images.githubusercontent.com/4748411/77731422-dbbaf480-703d-11ea-995f-2f2c7cb7fd05.png)

**Comment by jamming** [comment]
It is very difficult to clearly printing some symbols(such as '#' or '②' )on the 3D print case. So in the next batch of products, all USB 2 version ports will be identified as 'USB2.0'.  All USB 3 version ports will be identified as 'USB3.0'.  USB port number will no longer be printed on the case.

**Comment by bys1123** [comment]
![image](https://user-images.githubusercontent.com/4748411/78102854-edc1dc00-741d-11ea-87e5-3160b41b7bef.png)
@jamming Will this works?

**Comment by hamishwillee** [comment]
@jamming That's disappointing, but pragmatic and workable.

**Comment by jamming** [comment]
> ![image](https://user-images.githubusercontent.com/4748411/78102854-edc1dc00-741d-11ea-87e5-3160b41b7bef.png)
> @jamming Will this works?
 @bys1123 
①② can't clearly printing on the 3D print case
