### ISSUE TITLE
Doc Bug: VTOL w/o Airspeed Sensor · PX4 User Guide

### ISSUE THREAD

**Issue by George-avy** [PX4/px4_user_guide#740]
The page states:

> To tell the flight controller it will fly without an airspeed sensor you need to set the airspeed mode (FW_ARSP_MODE) to 'declare airspeed invalid' **(2)**.

whereas the correct value for FW_ARSP_MODE for disabled airspeed is 1, as per https://docs.px4.io/master/en/advanced_config/parameter_reference.html#FW_ARSP_MODE

Bug Page: [VTOL w/o Airspeed Sensor · PX4 User Guide](https://docs.px4.io/master/en/config_vtol/vtol_without_airspeed_sensor.html)

**Comment by George-avy** [comment]
Same a bit below on the page: 

> QUICK OVERVIEW OF RELEVANT PARAMETERS

    FW_ARSP_MODE: Declare invalid (2)

**Comment by hamishwillee** [comment]
Thanks @George-avy - much appreciated.
Fixed in master, v1.11 and v1.10 docs brances.
