### ISSUE TITLE
Doc Bug: Drotek Pixhawk 3 Pro (FMUv4pro) · PX4 User Guide

### ISSUE THREAD

**Issue by mrpollo** [PX4/px4_user_guide#784]
Link to pixhawk.drotek.com is no longer valid.

![Screen Shot 2020-08-06 at 8 08 47 AM](https://user-images.githubusercontent.com/317648/89548603-17b85000-d7bc-11ea-971a-c28f4358c5bd.png)

Bug Page: [Drotek Pixhawk 3 Pro (FMUv4pro) · PX4 User Guide](http://docs.px4.io/master/en/flight_controller/pixhawk3_pro.html)

**Comment by hamishwillee** [comment]
Hi @Paul-DROTEK The link to "Main hardware documentation" formerly at https://pixhawk.drotek.com/en/ no longer works. Can you point me to the updated link? Obviously I don't know exactly what is at that link, but I am expecting design files like at https://github.com/pixhawk/Hardware

**Comment by Paul-DROTEK** [comment]
Hi @mrpollo and thanks @hamishwillee for reaching out to me.

I am not really sure what happen with the dead link above.
Nonetheless you are still able to reach our gitbook product page related to the Pixhawk 3 Pro by using the link below :
https://drotek.gitbook.io/pixhawk-3-pro/

The hardware and pinout ressources are accessible here : https://drotek.gitbook.io/pixhawk-3-pro/hardware

Please @hamishwillee let me know wether the links provided are okay. @mrpollo feel free to reach us out [here ](https://electronics.drotek.com/after-sale-service/) if you need any further details.

**Comment by hamishwillee** [comment]
Thanks @Paul-DROTEK - those links look good. 

FWIW They probably actually wanted open-design schematics, but I am pretty sure that these were not supplied (ever) for this FMU version/board. Your links are the "right replacements" that I wanted here :-)
