### ISSUE TITLE
Doc Bug: PMW3901 · PX4 User Guide

### ISSUE THREAD

**Issue by muramura** [PX4/px4_user_guide#826]
DESCRIBE PROBLEM WITH DOCS HERE

Bug Page: [PMW3901 · PX4 User Guide](https://docs.px4.io/master/en/sensor/pmw3901.html#thone_thoneflow_3901U)

PR #12148 has been merged.

「This sensor is not yet supported - waiting on https://github.com/PX4/Firmware/pull/12148」

**Comment by hamishwillee** [comment]
Thanks very much. FYI You can always make these kind of PRs yourself - just click the edit button on any page to create a PR

![image](https://user-images.githubusercontent.com/5368500/95925544-c9e84580-0e05-11eb-81b1-128e9a975813.png)
