### ISSUE TITLE
Add takeoff information to altitude and position control mode docs

### ISSUE THREAD

**Issue by hamishwillee** [PX4/px4_user_guide#96]
For altitude and position mode, multicopter, add not about what counts as "takeoff"/how to takeoff.

The line to add is something along the lines of:

> The vehicle will take off if the stick is raised above 62.5% percent.

Origin of discussion is here: https://github.com/PX4/Devguide/pull/346#discussion_r151011496

**Comment by hamishwillee** [comment]
@dagar The statement "The vehicle will take off if the stick is raised above 62.5% percent." is true (it is hard coded) but what does this % refer to?

I THINK that it refers to the full range from the throttle stick bottom position. So in effect, to just above the large dead zone in the middle. Would that be correct?

**Comment by dagar** [comment]
Yes it's the full range starting from the bottom. It makes more sense when the throttle stick is spring loaded and centers itself.

**Comment by bys1123** [comment]
@hamishwillee I think this should add to doc when you have time.

**Comment by hamishwillee** [comment]
Done in #433

**Comment by bys1123** [comment]
Wow, so fast, thanks!
